export const BanfMainWnd = {
  objName: "TFPanel",
  name: "dashBoard",
  dataFieldName: "",
  css: "cssPanel",
  backgroundColor: "white",
  color: "rgb(0, 0, 0)",
  borderColor: "rgb(87, 86, 86)",
  borderWidth: "1.11111px",
  borderRadius: "2px",
  opacity: "1",
  blur: 0,
  placeItems: "stretch normal",
  justifyContent: "left",
  alignItems: "stretch",
  gridLeft: null,
  gridTop: null,
  gridWidth: null,
  gridHeight: null,
  gap: "",
  left: 4,
  top: 31,
  width: "100%",
  height: "100%",
  zIndex: "auto",
  margin: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marginBottom: "0px",
  padding: "0px",
  paddingTop: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingBottom: "0px",
  overflow: "hidden",
  visible: true,
  display: "grid",
  position: "relative",
  flexDirection: "row",
  gridLayout: "21x21",
  children: [
    {
      objName: "TFPanel",
      name: "gridContainerBanf",
      dataFieldName: "",
      css: ".cssContainerPanel",
      backgroundColor: "rgb(221, 221, 221)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "normal",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 10,
      gridWidth: 21,
      gridHeight: 12,
      gap: "",
      left: 1,
      top: 10,
      width: 21,
      height: 12,
      zIndex: "auto",
      margin: "4px",
      marginLeft: "4px",
      marginRight: "4px",
      marginTop: "4px",
      marginBottom: "4px",
      padding: "7px",
      paddingTop: "7px",
      paddingLeft: "7px",
      paddingRight: "7px",
      paddingBottom: "7px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "1x1",
      children: []
    },
    {
      objName: "TFPanel",
      name: "TFPanel175",
      dataFieldName: "",
      css: ".cssContainerPanel",
      backgroundColor: "rgb(136, 136, 136)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "normal",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 1,
      gridWidth: 21,
      gridHeight: 1,
      gap: "",
      left: 1,
      top: 1,
      width: 21,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "7px",
      paddingTop: "7px",
      paddingLeft: "7px",
      paddingRight: "7px",
      paddingBottom: "7px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "21x1",
      children: [
        {
          objName: "TFButton",
          name: "btnAddBanfHead",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 1,
          gridTop: 1,
          gridWidth: 3,
          gridHeight: 1,
          gap: "",
          left: 1,
          top: 1,
          width: 3,
          height: "35px",
          zIndex: "auto",
          margin: "0px 0px 3px 4px",
          marginLeft: "4px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "neue Banf vorbereiten",
          glyph: "circle-plus",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnEditBanfHead",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 5,
          gridTop: 1,
          gridWidth: 3,
          gridHeight: 1,
          gap: "",
          left: 5,
          top: 1,
          width: 3,
          height: "35px",
          zIndex: "auto",
          margin: "0px 0px 3px 4px",
          marginLeft: "4px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Banf bearbeiten",
          glyph: "pencil",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnDeleteBanfHead",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(128, 0, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 9,
          gridTop: 1,
          gridWidth: 3,
          gridHeight: 1,
          gap: "",
          left: 9,
          top: 1,
          width: 3,
          height: "35px",
          zIndex: "auto",
          margin: "0px 0px 3px 4px",
          marginLeft: "4px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Banf löschen",
          glyph: "circle-minus",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFSelectBox",
          name: "selectUser",
          dataFieldName: "",
          css: "cssContainerPanel",
          backgroundColor: "rgba(0, 0, 0, 0)",
          color: "rgb(0, 0, 0)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "center normal",
          justifyContent: "center",
          alignItems: "center",
          gridLeft: 14,
          gridTop: 1,
          gridWidth: 7,
          gridHeight: 1,
          gap: "",
          left: 14,
          top: 1,
          width: 7,
          height: 1,
          zIndex: "auto",
          margin: "3px",
          marginLeft: "3px",
          marginRight: "3px",
          marginTop: "3px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Mitarbeiter",
          captionLength: "7",
          value: null,
          editLength: "auto",
          appendix: "",
          appendixLength: "1",
          typ: "text",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnSelectUser",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(0, 128, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 21,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 21,
          top: 1,
          width: 1,
          height: "33px",
          zIndex: "auto",
          margin: "2px 0px 0px 1px",
          marginLeft: "1px",
          marginRight: "0px",
          marginTop: "2px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "check",
          glyphColor: "",
          children: []
        }
      ]
    },
    {
      objName: "TFPanel",
      name: "TFPanel2620",
      dataFieldName: "",
      css: ".cssContainerPanel",
      backgroundColor: "rgb(136, 136, 136)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 9,
      gridWidth: 21,
      gridHeight: 1,
      gap: "",
      left: 1,
      top: 9,
      width: 21,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "7px",
      paddingTop: "7px",
      paddingLeft: "7px",
      paddingRight: "7px",
      paddingBottom: "7px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "21x1",
      children: [
        {
          objName: "TFButton",
          name: "btnAddBanf",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 1,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 30,
          gap: "",
          left: 1,
          top: 1,
          width: 1,
          height: "35px",
          zIndex: "auto",
          margin: "3px",
          marginLeft: "3px",
          marginRight: "3px",
          marginTop: "3px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "circle-plus",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnEditBanf",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 3,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 30,
          gap: "",
          left: 3,
          top: 1,
          width: 1,
          height: "35px",
          zIndex: "auto",
          margin: "3px",
          marginLeft: "3px",
          marginRight: "3px",
          marginTop: "3px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "pen",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnDeleteBanf",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(128, 0, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 5,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 5,
          top: 1,
          width: 1,
          height: "35px",
          zIndex: "auto",
          margin: "3px",
          marginLeft: "3px",
          marginRight: "3px",
          marginTop: "3px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "circle-minus",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnFreigabe",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(0, 128, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 20,
          gridTop: 1,
          gridWidth: 2,
          gridHeight: 32,
          gap: "",
          left: 20,
          top: 1,
          width: 2,
          height: "35px",
          zIndex: "auto",
          margin: "3px",
          marginLeft: "3px",
          marginRight: "3px",
          marginTop: "3px",
          marginBottom: "3px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "hand-holding",
          glyphColor: "",
          children: []
        }
      ]
    },
    {
      objName: "TFPanel",
      name: "gridContainerBanfHead",
      dataFieldName: "",
      css: ".cssContainerPanel",
      backgroundColor: "rgb(204, 204, 204)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "normal",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 2,
      gridWidth: 21,
      gridHeight: 7,
      gap: "",
      left: 1,
      top: 2,
      width: 21,
      height: 7,
      zIndex: "auto",
      margin: "4px",
      marginLeft: "4px",
      marginRight: "4px",
      marginTop: "4px",
      marginBottom: "4px",
      padding: "7px",
      paddingTop: "7px",
      paddingLeft: "7px",
      paddingRight: "7px",
      paddingBottom: "7px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "1x1",
      children: []
    }
  ]
}


export const inpBANF = {
  objName: "TFPanel",
  name: "dashBoard",
  dataFieldName: "",
  css: "cssPanel",
  backgroundColor: "rgb(230, 230, 230)",
  color: "rgb(0, 0, 0)",
  borderColor: "rgb(87, 86, 86)",
  borderWidth: "1.11111px",
  borderRadius: "2px",
  opacity: "1",
  blur: 0,
  placeItems: "stretch normal",
  justifyContent: "left",
  alignItems: "stretch",
  gridLeft: null,
  gridTop: null,
  gridWidth: null,
  gridHeight: null,
  gap: "",
  left: 260,
  top: 110,
  width: "70%",
  height: "90%",
  zIndex: "auto",
  margin: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marginBottom: "0px",
  padding: "0px",
  paddingTop: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingBottom: "0px",
  overflow: "hidden",
  visible: true,
  display: "grid",
  position: "relative",
  flexDirection: "row",
  gridLayout: "13x20",
  children: [
    {
      objName: "TFPanel",
      name: "TFPanel478",
      dataFieldName: "",
      css: "cssPanel",
      backgroundColor: "rgb(255, 255, 255)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 1,
      gridWidth: 21,
      gridHeight: 1,
      gap: "",
      left: 1,
      top: 1,
      width: 21,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "1px",
      paddingTop: "1px",
      paddingLeft: "1px",
      paddingRight: "1px",
      paddingBottom: "1px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "13x3",
      children: [
        {
          objName: "TFLabel",
          name: "labelBanfBez",
          dataFieldName: "",
          css: "cssLabel",
          backgroundColor: "rgb(255, 255, 255)",
          color: "black",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "center",
          justifyContent: "start",
          alignItems: "center",
          gridLeft: 1,
          gridTop: 1,
          gridWidth: 12,
          gridHeight: 2,
          gap: "",
          left: 1,
          top: 1,
          width: 12,
          height: 2,
          zIndex: "auto",
          margin: "0px 0px 0px 10px",
          marginLeft: "10px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "1x1",
          caption: "Label",
          textAlign: "left",
          font: "Arial",
          fontWeight: "bold",
          fontSize: "1.25em",
          children: []
        },
        {
          objName: "TFButton",
          name: "TFButton812",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(204, 204, 204)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(204, 204, 204)",
          borderWidth: "0px",
          borderRadius: "0px",
          shadow: "0px",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 13,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 3,
          gap: "",
          left: 13,
          top: 1,
          width: 1,
          height: 3,
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "pen-clip",
          glyphColor: "rgb(68, 68, 68)",
          children: []
        },
        {
          objName: "TFLabel",
          name: "labelBanfDetails",
          dataFieldName: "",
          css: "cssLabel",
          backgroundColor: "rgba(0, 0, 0, 0)",
          color: "black",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "center",
          justifyContent: "start",
          alignItems: "center",
          gridLeft: 1,
          gridTop: 3,
          gridWidth: 12,
          gridHeight: 1,
          gap: "",
          left: 1,
          top: 3,
          width: 12,
          height: 1,
          zIndex: "auto",
          margin: "0px 0px 0px 10px",
          marginLeft: "10px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "1x1",
          caption: "Label",
          textAlign: "left",
          font: "Arial",
          fontWeight: "400",
          fontSize: "0.9em",
          children: []
        }
      ]
    },
    {
      objName: "TFEdit",
      name: "editPos",
      dataFieldName: "POSITIONSTEXT",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 3,
      gridWidth: 5,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 3,
      width: 5,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Position",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editMenge",
      dataFieldName: "MENGE",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 5,
      gridWidth: 5,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 5,
      width: 5,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Menge",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selMengenEinheit",
      dataFieldName: "MENGENEINHEIT",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 6,
      gridWidth: 4,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 6,
      width: 4,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Mengen-Einheit",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnSelectEinheit",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch center",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 6,
      gridTop: 6,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 6,
      top: 6,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editPreis",
      dataFieldName: "PREIS",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 7,
      gridWidth: 5,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 7,
      width: 5,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Preis",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFLabel",
      name: "TFLabel856",
      dataFieldName: "",
      css: "cssLabel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "black",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center",
      justifyContent: "start",
      alignItems: "center",
      gridLeft: 7,
      gridTop: 7,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 7,
      top: 7,
      width: 1,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "1x1",
      caption: "[EURO]",
      textAlign: "left",
      font: "Arial",
      fontWeight: "bold",
      fontSize: "1em",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "editWarengruppe",
      dataFieldName: "WARENGRUPPE",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 8,
      gridWidth: 10,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 8,
      width: 10,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Warengruppe",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnWarengrp",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 12,
      gridTop: 8,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 12,
      top: 8,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editLiefertermin",
      dataFieldName: "LIEFERDATUM",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 9,
      gridWidth: 7,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 9,
      width: 7,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Liefertermin",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "date",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selLieferant",
      dataFieldName: "LIEFERANT",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 10,
      gridWidth: 11,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 10,
      width: 11,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Lieferant",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnLieferant",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 13,
      gridTop: 10,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 13,
      top: 10,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selWerk",
      dataFieldName: "WERK",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 11,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 11,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Werk",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selEinkGrp",
      dataFieldName: "EINKAEUFERGRUPPE",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 12,
      gridWidth: 6,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 12,
      width: 6,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Einkäufer-Gruppe",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selEinkOrg",
      dataFieldName: "EINKAUFSORGANISATION",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 13,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 13,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Einkaufs-Organisation",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editAnforderer",
      dataFieldName: "ANFORDERER",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 14,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 14,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Anforderer",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editBemerkung",
      dataFieldName: "BEMERKUNG",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 15,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 15,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Bemerkung / Kommentar(e)",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selSachkonto",
      dataFieldName: "SACHKONTO",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 16,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 16,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Sachkonto",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selAuftrag",
      dataFieldName: "AUFTRAG",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 17,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 17,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Auftrag",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnSachkonto",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 10,
      gridTop: 16,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 10,
      top: 16,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnAuftrag",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 10,
      gridTop: 17,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 10,
      top: 17,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFPanel",
      name: "TFPanel9688",
      dataFieldName: "",
      css: "cssPanel",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 19,
      gridWidth: 13,
      gridHeight: 2,
      gap: "",
      left: 1,
      top: 19,
      width: 13,
      height: 2,
      zIndex: "auto",
      margin: "0px 0px 4px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "4px",
      padding: "3px",
      paddingTop: "3px",
      paddingLeft: "3px",
      paddingRight: "3px",
      paddingBottom: "3px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "5x1",
      children: [
        {
          objName: "TFButton",
          name: "btnOk",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 2,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 2,
          top: 1,
          width: 1,
          height: "35px",
          zIndex: "auto",
          margin: "0px 0px 0px 4px",
          marginLeft: "4px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Speichern",
          glyph: "circle-check",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnAbort",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(255, 51, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 4,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 4,
          top: 1,
          width: 1,
          height: "35px",
          zIndex: "auto",
          margin: "0px 0px 0px 4px",
          marginLeft: "4px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Abbruch",
          glyph: "circle-xmark",
          glyphColor: "",
          children: []
        }
      ]
    },
    {
      objName: "TFButton",
      name: "btnWerk",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 10,
      gridTop: 11,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 10,
      top: 11,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px",
      marginLeft: "5px",
      marginRight: "5px",
      marginTop: "5px",
      marginBottom: "5px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnEinkGrp",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 8,
      gridTop: 12,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 8,
      top: 12,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px",
      marginLeft: "5px",
      marginRight: "5px",
      marginTop: "5px",
      marginBottom: "5px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnEinkOrg",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 10,
      gridTop: 13,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 10,
      top: 13,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px",
      marginLeft: "5px",
      marginRight: "5px",
      marginTop: "5px",
      marginBottom: "5px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "editFeld_K",
      dataFieldName: "FELD_K",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 8,
      gridTop: 3,
      gridWidth: 2,
      gridHeight: 1,
      gap: "",
      left: 8,
      top: 3,
      width: 2,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Feld K",
      captionLength: 7,
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: 1,
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "editFeld_P",
      dataFieldName: "FELD_P",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 10,
      gridTop: 3,
      gridWidth: 2,
      gridHeight: 1,
      gap: "",
      left: 10,
      top: 3,
      width: 2,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Feld P ",
      captionLength: 8,
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selectMaterial",
      dataFieldName: "MATERIAL",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 8,
      gridTop: 5,
      gridWidth: 4,
      gridHeight: 1,
      gap: "",
      left: 8,
      top: 5,
      width: 4,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Material",
      captionLength: "7",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnMaterial",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 12,
      gridTop: 5,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 12,
      top: 5,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editKurztext",
      dataFieldName: "KURZTEXT",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 4,
      gridWidth: 10,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 4,
      width: 10,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Kurztext",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFPanel",
      name: "TFPanel364",
      dataFieldName: "",
      css: "cssPanel",
      backgroundColor: "rgb(102, 102, 102)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "7px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 11,
      gridTop: 13,
      gridWidth: 3,
      gridHeight: 6,
      gap: "",
      left: 11,
      top: 13,
      width: 3,
      height: 6,
      zIndex: "auto",
      margin: "1em",
      marginLeft: "1em",
      marginRight: "1em",
      marginTop: "1em",
      marginBottom: "1em",
      padding: "2px",
      paddingTop: "2px",
      paddingLeft: "2px",
      paddingRight: "2px",
      paddingBottom: "2px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "4x5",
      children: [
        {
          objName: "TFPanel",
          name: "TFPanel455",
          dataFieldName: "",
          css: "cssPanel",
          backgroundColor: "rgb(0, 0, 128)",
          color: "rgb(0, 0, 0)",
          borderColor: "rgb(87, 86, 86)",
          borderWidth: "1.11111px",
          borderRadius: "7px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "left",
          alignItems: "stretch",
          gridLeft: 1,
          gridTop: 1,
          gridWidth: 5,
          gridHeight: 1,
          gap: "",
          left: 1,
          top: 1,
          width: 5,
          height: 1,
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "7px",
          paddingTop: "7px",
          paddingLeft: "7px",
          paddingRight: "7px",
          paddingBottom: "7px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "relative",
          flexDirection: "row",
          gridLayout: "5x1",
          children: [
            {
              objName: "TFLabel",
              name: "TFLabel901",
              dataFieldName: "",
              css: "cssLabel",
              backgroundColor: "rgba(0, 0, 0, 0)",
              color: "rgb(255, 255, 255)",
              borderColor: "rgb(0, 0, 0)",
              borderWidth: "0px",
              borderRadius: "0px",
              opacity: "1",
              blur: "blur(0px)",
              placeItems: "center",
              justifyContent: "start",
              alignItems: "center",
              gridLeft: 1,
              gridTop: 1,
              gridWidth: 3,
              gridHeight: 1,
              gap: "",
              left: 1,
              top: 1,
              width: 3,
              height: 1,
              zIndex: "auto",
              margin: "0px",
              marginLeft: "0px",
              marginRight: "0px",
              marginTop: "0px",
              marginBottom: "0px",
              padding: "0px",
              paddingTop: "0px",
              paddingLeft: "0px",
              paddingRight: "0px",
              paddingBottom: "0px",
              overflow: "hidden",
              visible: true,
              display: "grid",
              position: "static",
              flexDirection: "row",
              gridLayout: "1x1",
              caption: "Anlagen ...",
              textAlign: "left",
              font: "Arial",
              fontWeight: "bold",
              fontSize: "1em",
              children: []
            },
            {
              objName: "TFButton",
              name: "btnDeleteAttachment",
              dataFieldName: "",
              css: "cssButton01",
              backgroundColor: "rgb(128, 0, 0)",
              color: "rgb(255, 255, 255)",
              borderColor: "rgb(0, 0, 0)",
              borderWidth: "1.11111px",
              borderRadius: "0px",
              opacity: "1",
              blur: "blur(0px)",
              placeItems: "stretch normal",
              justifyContent: "center",
              alignItems: "stretch",
              gridLeft: 5,
              gridTop: 1,
              gridWidth: 1,
              gridHeight: 1,
              gap: "",
              left: 5,
              top: 1,
              width: 1,
              height: "30px",
              zIndex: "auto",
              margin: "0px",
              marginLeft: "0px",
              marginRight: "0px",
              marginTop: "0px",
              marginBottom: "0px",
              padding: "0px",
              paddingTop: "0px",
              paddingLeft: "0px",
              paddingRight: "0px",
              paddingBottom: "0px",
              overflow: "visible",
              visible: true,
              display: "grid",
              position: "static",
              flexDirection: "row",
              gridLayout: "2x1",
              caption: "",
              glyph: "circle-minus",
              glyphColor: "",
              children: []
            }
          ]
        },
        {
          objName: "TFListBox",
          name: "listboxAttachment",
          dataFieldName: "",
          css: "cssObject",
          backgroundColor: "rgba(4, 4, 4, 0.32)",
          color: "rgb(0, 0, 0)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "center normal",
          justifyContent: "center",
          alignItems: "center",
          gridLeft: 1,
          gridTop: 4,
          gridWidth: 5,
          gridHeight: 2,
          gap: "",
          left: 1,
          top: 4,
          width: 5,
          height: 2,
          zIndex: "auto",
          margin: "2px",
          marginLeft: "2px",
          marginRight: "2px",
          marginTop: "2px",
          marginBottom: "2px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "flex",
          position: "static",
          flexDirection: "column",
          gridLayout: "0x0",
          children: []
        },
        {
          objName: "TFPanel",
          name: "dropBoxPanel",
          dataFieldName: "",
          css: ".cssContainerPanel",
          backgroundColor: "rgb(221, 221, 221)",
          color: "rgb(0, 0, 0)",
          borderColor: "rgb(87, 86, 86)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "normal",
          alignItems: "stretch",
          gridLeft: 1,
          gridTop: 2,
          gridWidth: 5,
          gridHeight: 2,
          gap: "",
          left: 1,
          top: 2,
          width: 5,
          height: 2,
          zIndex: "auto",
          margin: "2px",
          marginLeft: "2px",
          marginRight: "2px",
          marginTop: "2px",
          marginBottom: "2px",
          padding: "7px",
          paddingTop: "7px",
          paddingLeft: "7px",
          paddingRight: "7px",
          paddingBottom: "7px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "relative",
          flexDirection: "row",
          gridLayout: "1x1",
          children: []
        }
      ]
    }
  ]
}

export const banfExport = {
  objName: "TFPanel",
  name: "dashBoard",
  dataFieldName: "",
  css: "cssPanel",
  backgroundColor: "rgb(237, 237, 237)",
  color: "rgb(0, 0, 0)",
  borderColor: "rgb(87, 86, 86)",
  borderWidth: "1.11111px",
  borderRadius: "2px",
  opacity: "1",
  blur: 0,
  placeItems: "stretch normal",
  justifyContent: "left",
  alignItems: "stretch",
  gridLeft: null,
  gridTop: null,
  gridWidth: null,
  gridHeight: null,
  gap: "",
  left: 433,
  top: 320,
  width: "50%",
  height: "60%",
  zIndex: "auto",
  margin: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marginBottom: "0px",
  padding: "0px",
  paddingTop: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingBottom: "0px",
  overflow: "hidden",
  visible: true,
  display: "grid",
  position: "relative",
  flexDirection: "row",
  gridLayout: "21x21",
  children: [
    {
      objName: "TFPanel",
      name: "TFPanel253",
      dataFieldName: "",
      css: ".cssContainerPanel",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "normal",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 20,
      gridWidth: 21,
      gridHeight: 2,
      gap: "",
      left: 1,
      top: 20,
      width: 21,
      height: 2,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "-4px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "21x1",
      children: [
        {
          objName: "TFButton",
          name: "btnExport",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 7,
          gridTop: 1,
          gridWidth: 4,
          gridHeight: 2,
          gap: "",
          left: 7,
          top: 1,
          width: 4,
          height: 2,
          zIndex: "auto",
          margin: "5px",
          marginLeft: "5px",
          marginRight: "5px",
          marginTop: "5px",
          marginBottom: "5px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Daten übergeben",
          glyph: "",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnAbort",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(128, 0, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 12,
          gridTop: 1,
          gridWidth: 4,
          gridHeight: 2,
          gap: "",
          left: 12,
          top: 1,
          width: 4,
          height: 2,
          zIndex: "auto",
          margin: "5px",
          marginLeft: "5px",
          marginRight: "5px",
          marginTop: "5px",
          marginBottom: "5px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Vorgang abbrechen",
          glyph: "",
          glyphColor: "",
          children: []
        }
      ]
    },
    {
      objName: "TFListBox",
      name: "listBoxSource",
      dataFieldName: "",
      css: "cssObject",
      backgroundColor: "rgba(4, 4, 4, 0.32)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 3,
      gridWidth: 9,
      gridHeight: 14,
      gap: "",
      left: 2,
      top: 3,
      width: 9,
      height: 14,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "flex",
      position: "static",
      flexDirection: "column",
      gridLayout: "0x0",
      children: []
    },
    {
      objName: "TFListBox",
      name: "listBoxDestination",
      dataFieldName: "",
      css: "cssObject",
      backgroundColor: "rgba(4, 4, 4, 0.32)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 12,
      gridTop: 3,
      gridWidth: 9,
      gridHeight: 14,
      gap: "",
      left: 12,
      top: 3,
      width: 9,
      height: 14,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "flex",
      position: "static",
      flexDirection: "column",
      gridLayout: "0x0",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnPlus",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(95, 138, 35)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 11,
      gridTop: 7,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 11,
      top: 7,
      width: 1,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "",
      glyph: "circle-right",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnMinus",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(128, 0, 0)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 11,
      gridTop: 12,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 11,
      top: 12,
      width: 1,
      height: 1,
      zIndex: "auto",
      margin: "0px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "",
      glyph: "circle-left",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFLabel",
      name: "TFLabel1175",
      dataFieldName: "",
      css: "cssLabel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "black",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "center",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 12,
      gridTop: 2,
      gridWidth: 9,
      gridHeight: 1,
      gap: "",
      left: 12,
      top: 2,
      width: 9,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "1x1",
      caption: "Zielfeder / Reihenfolge (Steuerung mit ALT+Pfeiltasten)",
      textAlign: "center",
      font: "Arial",
      fontWeight: "bold",
      fontSize: "1em",
      children: []
    },
    {
      objName: "TFLabel",
      name: "TFLabel1244",
      dataFieldName: "",
      css: "cssLabel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "black",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "center",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 2,
      gridWidth: 9,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 2,
      width: 9,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "1x1",
      caption: "alle verfügbaren Felder",
      textAlign: "center",
      font: "Arial",
      fontWeight: "400",
      fontSize: "1em",
      children: []
    }
  ]
}


export const sendBanf = {
  objName: "TFPanel",
  name: "dashBoard",
  dataFieldName: "",
  css: "cssPanel",
  backgroundColor: "rgb(204, 204, 204)",
  color: "rgb(0, 0, 0)",
  borderColor: "rgb(87, 86, 86)",
  borderWidth: "1.11111px",
  borderRadius: "2px",
  opacity: "1",
  blur: 0,
  placeItems: "stretch normal",
  justifyContent: "left",
  alignItems: "stretch",
  gridLeft: null,
  gridTop: null,
  gridWidth: null,
  gridHeight: null,
  gap: "",
  left: 428,
  top: 304,
  width: "50%",
  height: "50%",
  zIndex: "auto",
  margin: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marginBottom: "0px",
  padding: "0px",
  paddingTop: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingBottom: "0px",
  overflow: "hidden",
  visible: true,
  display: "grid",
  position: "relative",
  flexDirection: "row",
  gridLayout: "21x21",
  children: [
    {
      objName: "TFPanel",
      name: "TFPanel179",
      dataFieldName: "",
      css: ".cssContainerPanel",
      backgroundColor: "rgb(68, 68, 68)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "normal",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 1,
      gridWidth: 21,
      gridHeight: 2,
      gap: "",
      left: 1,
      top: 1,
      width: 21,
      height: 2,
      zIndex: "auto",
      margin: "2px",
      marginLeft: "2px",
      marginRight: "2px",
      marginTop: "2px",
      marginBottom: "2px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "10x1",
      children: [
        {
          objName: "TFButton",
          name: "TFButton47",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(102, 102, 102)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 10,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 10,
          top: 1,
          width: 1,
          height: "40px",
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "square-envelope",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFLabel",
          name: "TFLabel432",
          dataFieldName: "",
          css: "cssLabel",
          backgroundColor: "rgba(0, 0, 0, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          opacity: "1",
          blur: "blur(0px)",
          placeItems: "center",
          justifyContent: "center",
          alignItems: "center",
          gridLeft: 1,
          gridTop: 1,
          gridWidth: 8,
          gridHeight: 1,
          gap: "",
          left: 1,
          top: 1,
          width: 8,
          height: 1,
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "1x1",
          caption: "Versand der BANF-Vorlage an den oder die verarntwortlichen Mitarbeiter",
          textAlign: "center",
          font: "Arial",
          fontWeight: "bold",
          fontSize: "1em",
          children: []
        }
      ]
    },
    {
      objName: "TFEdit",
      name: "editHint",
      dataFieldName: "",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 5,
      gridWidth: 19,
      gridHeight: 3,
      gap: "",
      left: 2,
      top: 5,
      width: 19,
      height: 3,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "1x4",
      caption: "Hinweis für den Bearbeiter",
      labelPosition: "top",
      captionLength: "4.5",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFLabel",
      name: "TFLabel768",
      dataFieldName: "",
      css: "cssLabel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "black",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "center",
      justifyContent: "start",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 9,
      gridWidth: 19,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 9,
      width: 19,
      height: 1,
      zIndex: "auto",
      margin: "0px 0px 0px 1em",
      marginLeft: "1em",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "1x1",
      caption: "Bitte wählen Sie aus, an wen diese Vorlage zu senden ist :",
      textAlign: "left",
      font: "Arial",
      fontWeight: "400",
      fontSize: "1em",
      children: []
    },
    {
      objName: "TFListCheckbox",
      name: "selectAdress",
      dataFieldName: "",
      css: "cssObject",
      backgroundColor: "rgba(0, 0, 0, 0.1)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 10,
      gridWidth: 19,
      gridHeight: 8,
      gap: "",
      left: 2,
      top: 10,
      width: 19,
      height: 8,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "auto",
      visible: true,
      display: "block",
      position: "static",
      flexDirection: "column",
      gridLayout: "0x0",
      children: []
    },
    {
      objName: "TFPanel",
      name: "TFPanel1980",
      dataFieldName: "",
      css: ".cssContainerPanel",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "7px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 19,
      gridWidth: 21,
      gridHeight: 3,
      gap: "",
      left: 1,
      top: 19,
      width: 21,
      height: 3,
      zIndex: "auto",
      margin: "2px",
      marginLeft: "2px",
      marginRight: "2px",
      marginTop: "2px",
      marginBottom: "2px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "7x1",
      children: [
        {
          objName: "TFButton",
          name: "btnSend",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 3,
          gridTop: 1,
          gridWidth: 3,
          gridHeight: 1,
          gap: "",
          left: 3,
          top: 1,
          width: 3,
          height: "40px",
          zIndex: "auto",
          margin: "10px 0px 0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "10px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "senden",
          glyph: "play",
          glyphColor: "",
          children: []
        }
      ]
    }
  ]
}