export const inpBANF = {
  objName: "TFPanel",
  name: "dashBoard",
  dataFieldName: "",
  css: "cssPanel",
  backgroundColor: "rgb(230, 230, 230)",
  color: "rgb(0, 0, 0)",
  borderColor: "rgb(87, 86, 86)",
  borderWidth: "1.11111px",
  borderRadius: "2px",
  shadow: "",
  opacity: "1",
  blur: 0,
  placeItems: "stretch normal",
  justifyContent: "left",
  alignItems: "stretch",
  gridLeft: null,
  gridTop: null,
  gridWidth: null,
  gridHeight: null,
  gap: "",
  left: 1072,
  top: 96,
  width: "50%",
  height: "94%",
  zIndex: "auto",
  margin: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marginBottom: "0px",
  padding: "0px",
  paddingTop: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingBottom: "0px",
  overflow: "hidden",
  visible: true,
  display: "grid",
  position: "relative",
  flexDirection: "row",
  gridLayout: "13x19",
  children: [
    {
      objName: "TFPanel",
      name: "TFPanel478",
      dataFieldName: "",
      css: "cssPanel",
      backgroundColor: "rgb(255, 255, 255)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "7px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 1,
      gridWidth: 21,
      gridHeight: 1,
      gap: "",
      left: 1,
      top: 1,
      width: 21,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "1px",
      paddingTop: "1px",
      paddingLeft: "1px",
      paddingRight: "1px",
      paddingBottom: "1px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "13x1",
      children: [
        {
          objName: "TFLabel",
          name: "labelBanfBez",
          dataFieldName: "",
          css: "cssLabel",
          backgroundColor: "rgb(255, 255, 255)",
          color: "black",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "center",
          justifyContent: "center",
          alignItems: "center",
          gridLeft: 1,
          gridTop: 1,
          gridWidth: 12,
          gridHeight: 1,
          gap: "",
          left: 1,
          top: 1,
          width: 12,
          height: 1,
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "1x1",
          caption: "Label",
          textAlign: "center",
          font: "Arial",
          fontWeight: "bold",
          fontSize: "1.5em",
          children: []
        },
        {
          objName: "TFButton",
          name: "TFButton812",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(255, 255, 255)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 13,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 13,
          top: 1,
          width: 1,
          height: 1,
          zIndex: "auto",
          margin: "1px 0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "1px",
          marginBottom: "1px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "pen-clip",
          glyphColor: "rgb(68, 68, 68)",
          children: []
        }
      ]
    },
    {
      objName: "TFEdit",
      name: "editPos",
      dataFieldName: "POSITIONSTEXT",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: "blur(0px)",
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 3,
      gridWidth: 5,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 3,
      width: 5,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Position",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editMenge",
      dataFieldName: "MENGE",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 4,
      gridWidth: 5,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 4,
      width: 5,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Menge",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selMengenEinheit",
      dataFieldName: "MENGENEINHEIT",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 5,
      gridWidth: 10,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 5,
      width: 10,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Mengen-Einheit",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnSelectEinheit",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch center",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 12,
      gridTop: 5,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 12,
      top: 5,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editPreis",
      dataFieldName: "PREIS",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 6,
      gridWidth: 5,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 6,
      width: 5,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Preis",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFLabel",
      name: "TFLabel856",
      dataFieldName: "",
      css: "cssLabel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "black",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center",
      justifyContent: "start",
      alignItems: "center",
      gridLeft: 7,
      gridTop: 6,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 7,
      top: 6,
      width: 1,
      height: 1,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "1x1",
      caption: "[EURO]",
      textAlign: "left",
      font: "Arial",
      fontWeight: "bold",
      fontSize: "",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "editWarengruppe",
      dataFieldName: "WARENGRUPPE",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 7,
      gridWidth: 10,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 7,
      width: 10,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Warengruppe",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnWarengrp",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 12,
      gridTop: 7,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 12,
      top: 7,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editLiefertermin",
      dataFieldName: "LIEFERDATUM",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 8,
      gridWidth: 7,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 8,
      width: 7,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Liefertermin",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "date",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selLieferant",
      dataFieldName: "LIEFERANT",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 9,
      gridWidth: 11,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 9,
      width: 11,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Lieferant",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnLieferant",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 13,
      gridTop: 9,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 13,
      top: 9,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selWerk",
      dataFieldName: "WERK",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 10,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 10,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Werk",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selEinkGrp",
      dataFieldName: "EINKAEUFERGRUPPE",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 11,
      gridWidth: 6,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 11,
      width: 6,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Einkäufer-Gruppe",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selEinkOrg",
      dataFieldName: "EINKAUFSORGANISATION",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 12,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 12,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Einkaufs-Organisation",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editAnforderer",
      dataFieldName: "ANFORDERER",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 13,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 13,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Anforderer",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editBemerkung",
      dataFieldName: "BEMERKUNG",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 14,
      gridWidth: 11,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 14,
      width: 11,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Bemerkung / Kommentar(e)",
      captionLength: "21",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selSachkonto",
      dataFieldName: "SACHKONTO",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 15,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 15,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Sachkonto",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFSelectBox",
      name: "selAuftrag",
      dataFieldName: "AUFTRAG",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 16,
      gridWidth: 8,
      gridHeight: 1,
      gap: "",
      left: 2,
      top: 16,
      width: 8,
      height: 1,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "Auftrag",
      captionLength: "21",
      value: null,
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnSachkonto",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 10,
      gridTop: 15,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 10,
      top: 15,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnAuftrag",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 10,
      gridTop: 16,
      gridWidth: 1,
      gridHeight: 1,
      gap: "",
      left: 10,
      top: 16,
      width: "35px",
      height: "35px",
      zIndex: "auto",
      margin: "5px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "5px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "...",
      glyph: "",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFPanel",
      name: "TFPanel9688",
      dataFieldName: "",
      css: "cssPanel",
      backgroundColor: "rgb(153, 153, 153)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "7px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 19,
      gridWidth: 13,
      gridHeight: 2,
      gap: "",
      left: 1,
      top: 19,
      width: 13,
      height: 2,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "7px",
      paddingTop: "7px",
      paddingLeft: "7px",
      paddingRight: "7px",
      paddingBottom: "7px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "5x1",
      children: [
        {
          objName: "TFButton",
          name: "btnOk",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 2,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 2,
          top: 1,
          width: 1,
          height: 1,
          zIndex: "auto",
          margin: "0px 0px 0px 4px",
          marginLeft: "4px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Speichern",
          glyph: "circle-check",
          glyphColor: "",
          children: []
        },
        {
          objName: "TFButton",
          name: "TFButton668",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(255, 51, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 4,
          gridTop: 1,
          gridWidth: 1,
          gridHeight: 1,
          gap: "",
          left: 4,
          top: 1,
          width: 1,
          height: 1,
          zIndex: "auto",
          margin: "0px 0px 0px 4px",
          marginLeft: "4px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "Abbruch",
          glyph: "circle-xmark",
          glyphColor: "",
          children: []
        }
      ]
    }
  ]
}


export const Katalog = {
  objName: "TFPanel",
  name: "dashBoard",
  dataFieldName: "",
  css: "cssPanel",
  backgroundColor: "rgb(204, 204, 204)",
  color: "rgb(0, 0, 0)",
  borderColor: "rgb(87, 86, 86)",
  borderWidth: "1.11111px",
  borderRadius: "2px",
  shadow: "",
  opacity: "1",
  blur: 0,
  placeItems: "stretch normal",
  justifyContent: "left",
  alignItems: "stretch",
  gridLeft: null,
  gridTop: null,
  gridWidth: null,
  gridHeight: null,
  gap: "",
  left: 685,
  top: 382,
  width: "20%",
  height: "40%",
  zIndex: "auto",
  margin: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marginBottom: "0px",
  padding: "0px",
  paddingTop: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingBottom: "0px",
  overflow: "hidden",
  visible: true,
  display: "grid",
  position: "relative",
  flexDirection: "row",
  gridLayout: "20x20",
  children: [
    {
      objName: "TFPanel",
      name: "TFPanel169",
      dataFieldName: "",
      css: "cssPanel",
      backgroundColor: "rgb(68, 68, 68)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(87, 86, 86)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "left",
      alignItems: "stretch",
      gridLeft: 1,
      gridTop: 1,
      gridWidth: 20,
      gridHeight: 2,
      gap: "",
      left: 1,
      top: 1,
      width: 20,
      height: 2,
      zIndex: "auto",
      margin: "0px",
      marginLeft: "0px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px 0px 0px 7px",
      paddingTop: "0px",
      paddingLeft: "7px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "relative",
      flexDirection: "row",
      gridLayout: "10x2",
      children: [
        {
          objName: "TFLabel",
          name: "caption1",
          dataFieldName: "",
          css: "cssLabel",
          backgroundColor: "rgba(0, 0, 0, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "center",
          justifyContent: "start",
          alignItems: "center",
          gridLeft: 1,
          gridTop: 1,
          gridWidth: 8,
          gridHeight: 1,
          gap: "",
          left: 1,
          top: 1,
          width: 8,
          height: 1,
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "1x1",
          caption: "Caption 1",
          textAlign: "left",
          font: "Arial",
          fontWeight: "bold",
          fontSize: "1em",
          children: []
        },
        {
          objName: "TFLabel",
          name: "caption2",
          dataFieldName: "",
          css: "cssLabel",
          backgroundColor: "rgba(0, 0, 0, 0)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "0px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "center",
          justifyContent: "start",
          alignItems: "center",
          gridLeft: 1,
          gridTop: 2,
          gridWidth: 8,
          gridHeight: 1,
          gap: "",
          left: 1,
          top: 2,
          width: 8,
          height: 1,
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "hidden",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "1x1",
          caption: "Caption 2",
          textAlign: "left",
          font: "Arial",
          fontWeight: "400",
          fontSize: "1em",
          children: []
        },
        {
          objName: "TFButton",
          name: "btnClose",
          dataFieldName: "",
          css: "cssButton01",
          backgroundColor: "rgb(95, 138, 35)",
          color: "rgb(255, 255, 255)",
          borderColor: "rgb(0, 0, 0)",
          borderWidth: "1.11111px",
          borderRadius: "0px",
          shadow: "",
          opacity: "1",
          blur: 0,
          placeItems: "stretch normal",
          justifyContent: "center",
          alignItems: "stretch",
          gridLeft: 9,
          gridTop: 1,
          gridWidth: 3,
          gridHeight: 2,
          gap: "",
          left: 9,
          top: 1,
          width: 3,
          height: 2,
          zIndex: "auto",
          margin: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          marginTop: "0px",
          marginBottom: "0px",
          padding: "0px",
          paddingTop: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          paddingBottom: "0px",
          overflow: "visible",
          visible: true,
          display: "grid",
          position: "static",
          flexDirection: "row",
          gridLayout: "2x1",
          caption: "",
          glyph: "circle-check",
          glyphColor: "",
          children: []
        }
      ]
    },
    {
      objName: "TFEdit",
      name: "editName",
      dataFieldName: "",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 4,
      gridWidth: 18,
      gridHeight: 3,
      gap: "",
      left: 2,
      top: 4,
      width: 18,
      height: 3,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "1x4",
      caption: "Eingabe",
      captionLength: "4.5",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnPlus",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(136, 136, 136)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 7,
      gridTop: 7,
      gridWidth: 2,
      gridHeight: 2,
      gap: "",
      left: 7,
      top: 7,
      width: 2,
      height: 2,
      zIndex: "auto",
      margin: "0px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "",
      glyph: "circle-plus",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnMinus",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(128, 0, 0)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 14,
      gridTop: 7,
      gridWidth: 2,
      gridHeight: 2,
      gap: "",
      left: 14,
      top: 7,
      width: 2,
      height: 2,
      zIndex: "auto",
      margin: "0px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "",
      glyph: "circle-minus",
      glyphColor: "",
      children: []
    },
    {
      objName: "TFListBox",
      name: "listBox",
      dataFieldName: "",
      css: "cssObject",
      backgroundColor: "rgba(4, 4, 4, 0.32)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 1,
      gridTop: 9,
      gridWidth: 20,
      gridHeight: 12,
      gap: "",
      left: 1,
      top: 9,
      width: 20,
      height: 12,
      zIndex: "auto",
      margin: "10px 7px 7px",
      marginLeft: "7px",
      marginRight: "7px",
      marginTop: "10px",
      marginBottom: "7px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "flex",
      position: "static",
      flexDirection: "column",
      gridLayout: "0x0",
      children: []
    }
  ]
}