import * as globals      from "./tfWebApp/globals.js";
import * as utils        from "./tfWebApp/utils.js";    
import * as dialogs      from "./tfWebApp/tfDialogs.js";

import * as forms                from "./forms.js";
import { TFgui }                 from "./tfWebApp/tfGUI.js";



const miniEmail = {
  objName: "TFPanel",
  name: "dashBoard",
  dataFieldName: "",
  css: "cssPanel",
  backgroundColor: "rgb(204, 204, 204)",
  color: "rgb(0, 0, 0)",
  borderColor: "rgb(87, 86, 86)",
  borderWidth: "1.11111px",
  borderRadius: "2px",
  opacity: "1",
  blur: 0,
  placeItems: "stretch normal",
  justifyContent: "left",
  alignItems: "stretch",
  gridLeft: null,
  gridTop: null,
  gridWidth: null,
  gridHeight: null,
  gap: "",
  left: 256,
  top: 274,
  width: "70%",
  height: "50%",
  zIndex: "auto",
  margin: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marginBottom: "0px",
  padding: "0px",
  paddingTop: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingBottom: "0px",
  overflow: "hidden",
  visible: true,
  display: "grid",
  position: "relative",
  flexDirection: "row",
  gridLayout: "21x21",
  children: [
    {
      objName: "TFEdit",
      name: "editAddress",
      dataFieldName: "",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 6,
      gridWidth: 19,
      gridHeight: 2,
      gap: "",
      left: 2,
      top: 6,
      width: 19,
      height: 2,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "an:",
      captionLength: "4",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFEdit",
      name: "editMessage",
      dataFieldName: "",
      css: "cssContainerPanel",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(0, 0, 0)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "0px",
      borderRadius: "0px",
      shadow: "",
      opacity: "1",
      blur: 0,
      placeItems: "center normal",
      justifyContent: "center",
      alignItems: "center",
      gridLeft: 2,
      gridTop: 12,
      gridWidth: 19,
      gridHeight: 2,
      gap: "",
      left: 2,
      top: 12,
      width: 19,
      height: 2,
      zIndex: "auto",
      margin: "3px",
      marginLeft: "3px",
      marginRight: "3px",
      marginTop: "3px",
      marginBottom: "3px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "hidden",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "msg:",
      captionLength: "4",
      value: "",
      editLength: "auto",
      appendix: "",
      appendixLength: "1",
      typ: "text",
      children: []
    },
    {
      objName: "TFButton",
      name: "btnSend",
      dataFieldName: "",
      css: "cssButton01",
      backgroundColor: "rgb(95, 138, 35)",
      color: "rgb(255, 255, 255)",
      borderColor: "rgb(0, 0, 0)",
      borderWidth: "1.11111px",
      borderRadius: "0px",
      opacity: "1",
      blur: 0,
      placeItems: "stretch normal",
      justifyContent: "center",
      alignItems: "stretch",
      gridLeft: 11,
      gridTop: 18,
      gridWidth: 2,
      gridHeight: 2,
      gap: "",
      left: 11,
      top: 18,
      width: 2,
      height: 2,
      zIndex: "auto",
      margin: "0px 0px 0px 4px",
      marginLeft: "4px",
      marginRight: "0px",
      marginTop: "0px",
      marginBottom: "0px",
      padding: "0px",
      paddingTop: "0px",
      paddingLeft: "0px",
      paddingRight: "0px",
      paddingBottom: "0px",
      overflow: "visible",
      visible: true,
      display: "grid",
      position: "static",
      flexDirection: "row",
      gridLayout: "2x1",
      caption: "send",
      glyph: "square-check",
      glyphColor: "",
      children: []
    }
  ]
}


export function sendMail()
{
  var gui     = new TFgui( null , miniEmail , {caption:"miniMail - TestProgramm"});

  gui.btnSend.callBack_onClick = function()
                                            {
                                               var mail = {
                                                            from        : "banfProcess@e-ms.de",
                                                            to          : this.gui.editAddress.value,
                                                            subject     : "testmail via nodeJS",
                                                            text        : this.gui.editMessage.value,
                                                            html        : "",
                                                            attachments : []
                                                          }   

                                                utils.webApiRequest('SENDMAIL', {mail:mail} );           
                                            }.bind({gui:gui})
}